name: cumulations_form_annotations
description: Annotation for cumulations_form_generators.
version: 1.0.2
homepage: https://github.com/ShridharBanavasi1997/cumulations_form_generators
repository: https://github.com/ShridharBanavasi1997/cumulations_form_generators.git
issue_tracker: https://github.com/ShridharBanavasi1997/cumulations_form_generators/issues

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
