name: cumulations_form_generators
description: This package is used to generate forms for data classes. It uses annotations to generate the form. The package also includes a form generator that generates the form based on the cumulation_form_annotations
version: 1.0.0-1
homepage: https://github.com/ShridharBanavasi1997/cumulations_form_generators
repository: https://github.com/ShridharBanavasi1997/cumulations_form_generators.git

environment:
  sdk: '>=2.18.1 <4.0.0'

dependencies:
  build: ^2.4.1
  source_gen: ^1.5.0
  cumulations_form_annotations: ^1.0.0
  analyzer: ^6.4.1

dev_dependencies:
  build_test:
  build_runner:
  lints: ^2.0.0
  test: ^1.16.0
